[project]
name = "pixel-forge"
dynamic = ["version"]
dependencies = [
    "amaranth >= 0.5.0",
    "amaranth-boards @ git+https://github.com/amaranth-lang/amaranth-boards.git@85d91df72a9d3ddb1498148a70e32f03027dd541",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc.git@a585f4c6465c220076bfb029c5d991761a9ae128",
    "amaranth-yosys >= 0.50.0.0.post120",
]
requires-python = ">=3.10"

[project.urls]
"Source Code" = "https://github.com/qbojj/PiexelForge.git"

[dependency-groups]
dev = [
    # Testing
    "pytest >= 8.0.0",
    "pytest-xdist == 3.5.0",
    "hypothesis == 6.99.6",
    # Other
    "pre-commit >= 2.20.0",
    "numpy >= 2.0.0"
]

[tool.setuptools]
py-modules= ["gpu"]

[tool.ruff.lint]
select = [
    "E", "F", "W",
    "I",
    "N",
    "UP",
    "C4",
]
ignore = [
    "F403", # "'from module import *' used; unable to detect undefined names"
    "F405", # "name may be undefined, or defined from star imports"
    "E501", # line too long
]

[tool.pytest.ini_options]
pythonpath = [
  ".",
]
addopts = [
  "-n", "logical",
]
markers = [
  "slow: marks tests as slow (run with '--run-slow')",
]
