# TCL File Generated by Component Editor 24.1
# Sat Jan 24 23:16:09 CET 2026
# DO NOT MODIFY


#
# gpu "gpu" v1.0
#  2026.01.24.23:16:09
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module gpu
#
set_module_property DESCRIPTION ""
set_module_property NAME gpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gpu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file graphics_pipeline_avalon_csr.sv SYSTEM_VERILOG PATH ../graphics_pipeline_avalon_csr.sv TOP_LEVEL_FILE


#
# parameters
#


#
# display items
#


#
# connection point avl_index
#
add_interface avl_index avalon start
set_interface_property avl_index addressUnits SYMBOLS
set_interface_property avl_index associatedClock clock
set_interface_property avl_index associatedReset reset
set_interface_property avl_index bitsPerSymbol 8
set_interface_property avl_index burstOnBurstBoundariesOnly false
set_interface_property avl_index burstcountUnits WORDS
set_interface_property avl_index doStreamReads false
set_interface_property avl_index doStreamWrites false
set_interface_property avl_index holdTime 0
set_interface_property avl_index linewrapBursts false
set_interface_property avl_index maximumPendingReadTransactions 0
set_interface_property avl_index maximumPendingWriteTransactions 0
set_interface_property avl_index readLatency 0
set_interface_property avl_index readWaitTime 1
set_interface_property avl_index setupTime 0
set_interface_property avl_index timingUnits Cycles
set_interface_property avl_index writeWaitTime 0
set_interface_property avl_index ENABLED true
set_interface_property avl_index EXPORT_OF ""
set_interface_property avl_index PORT_NAME_MAP ""
set_interface_property avl_index CMSIS_SVD_VARIABLES ""
set_interface_property avl_index SVD_ADDRESS_GROUP ""

add_interface_port avl_index avl_index__address address Output 32
add_interface_port avl_index avl_index__write write Output 1
add_interface_port avl_index avl_index__read read Output 1
add_interface_port avl_index avl_index__writedata writedata Output 32
add_interface_port avl_index avl_index__readdata readdata Input 32
add_interface_port avl_index avl_index__waitrequest waitrequest Input 1


#
# connection point avl_vertex
#
add_interface avl_vertex avalon start
set_interface_property avl_vertex addressUnits SYMBOLS
set_interface_property avl_vertex associatedClock clock
set_interface_property avl_vertex associatedReset reset
set_interface_property avl_vertex bitsPerSymbol 8
set_interface_property avl_vertex burstOnBurstBoundariesOnly false
set_interface_property avl_vertex burstcountUnits WORDS
set_interface_property avl_vertex doStreamReads false
set_interface_property avl_vertex doStreamWrites false
set_interface_property avl_vertex holdTime 0
set_interface_property avl_vertex linewrapBursts false
set_interface_property avl_vertex maximumPendingReadTransactions 0
set_interface_property avl_vertex maximumPendingWriteTransactions 0
set_interface_property avl_vertex readLatency 0
set_interface_property avl_vertex readWaitTime 1
set_interface_property avl_vertex setupTime 0
set_interface_property avl_vertex timingUnits Cycles
set_interface_property avl_vertex writeWaitTime 0
set_interface_property avl_vertex ENABLED true
set_interface_property avl_vertex EXPORT_OF ""
set_interface_property avl_vertex PORT_NAME_MAP ""
set_interface_property avl_vertex CMSIS_SVD_VARIABLES ""
set_interface_property avl_vertex SVD_ADDRESS_GROUP ""

add_interface_port avl_vertex avl_vertex__address address Output 32
add_interface_port avl_vertex avl_vertex__write write Output 1
add_interface_port avl_vertex avl_vertex__read read Output 1
add_interface_port avl_vertex avl_vertex__writedata writedata Output 32
add_interface_port avl_vertex avl_vertex__readdata readdata Input 32
add_interface_port avl_vertex avl_vertex__waitrequest waitrequest Input 1


#
# connection point avl_color
#
add_interface avl_color avalon start
set_interface_property avl_color addressUnits SYMBOLS
set_interface_property avl_color associatedClock pixel_clock
set_interface_property avl_color associatedReset pixel_reset
set_interface_property avl_color bitsPerSymbol 8
set_interface_property avl_color burstOnBurstBoundariesOnly false
set_interface_property avl_color burstcountUnits WORDS
set_interface_property avl_color doStreamReads false
set_interface_property avl_color doStreamWrites false
set_interface_property avl_color holdTime 0
set_interface_property avl_color linewrapBursts false
set_interface_property avl_color maximumPendingReadTransactions 0
set_interface_property avl_color maximumPendingWriteTransactions 0
set_interface_property avl_color readLatency 0
set_interface_property avl_color readWaitTime 1
set_interface_property avl_color setupTime 0
set_interface_property avl_color timingUnits Cycles
set_interface_property avl_color writeWaitTime 0
set_interface_property avl_color ENABLED true
set_interface_property avl_color EXPORT_OF ""
set_interface_property avl_color PORT_NAME_MAP ""
set_interface_property avl_color CMSIS_SVD_VARIABLES ""
set_interface_property avl_color SVD_ADDRESS_GROUP ""

add_interface_port avl_color avl_color__address address Output 32
add_interface_port avl_color avl_color__write write Output 1
add_interface_port avl_color avl_color__read read Output 1
add_interface_port avl_color avl_color__writedata writedata Output 32
add_interface_port avl_color avl_color__readdata readdata Input 32
add_interface_port avl_color avl_color__waitrequest waitrequest Input 1


#
# connection point avl_depthstencil
#
add_interface avl_depthstencil avalon start
set_interface_property avl_depthstencil addressUnits SYMBOLS
set_interface_property avl_depthstencil associatedClock pixel_clock
set_interface_property avl_depthstencil associatedReset pixel_reset
set_interface_property avl_depthstencil bitsPerSymbol 8
set_interface_property avl_depthstencil burstOnBurstBoundariesOnly false
set_interface_property avl_depthstencil burstcountUnits WORDS
set_interface_property avl_depthstencil doStreamReads false
set_interface_property avl_depthstencil doStreamWrites false
set_interface_property avl_depthstencil holdTime 0
set_interface_property avl_depthstencil linewrapBursts false
set_interface_property avl_depthstencil maximumPendingReadTransactions 0
set_interface_property avl_depthstencil maximumPendingWriteTransactions 0
set_interface_property avl_depthstencil readLatency 0
set_interface_property avl_depthstencil readWaitTime 1
set_interface_property avl_depthstencil setupTime 0
set_interface_property avl_depthstencil timingUnits Cycles
set_interface_property avl_depthstencil writeWaitTime 0
set_interface_property avl_depthstencil ENABLED true
set_interface_property avl_depthstencil EXPORT_OF ""
set_interface_property avl_depthstencil PORT_NAME_MAP ""
set_interface_property avl_depthstencil CMSIS_SVD_VARIABLES ""
set_interface_property avl_depthstencil SVD_ADDRESS_GROUP ""

add_interface_port avl_depthstencil avl_depthstencil__address address Output 32
add_interface_port avl_depthstencil avl_depthstencil__write write Output 1
add_interface_port avl_depthstencil avl_depthstencil__read read Output 1
add_interface_port avl_depthstencil avl_depthstencil__writedata writedata Output 32
add_interface_port avl_depthstencil avl_depthstencil__readdata readdata Input 32
add_interface_port avl_depthstencil avl_depthstencil__waitrequest waitrequest Input 1


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point ready
#
add_interface ready interrupt end
set_interface_property ready associatedAddressablePoint csr
set_interface_property ready associatedClock clock
set_interface_property ready associatedReset reset
set_interface_property ready bridgedReceiverOffset ""
set_interface_property ready bridgesToReceiver ""
set_interface_property ready ENABLED true
set_interface_property ready EXPORT_OF ""
set_interface_property ready PORT_NAME_MAP ""
set_interface_property ready CMSIS_SVD_VARIABLES ""
set_interface_property ready SVD_ADDRESS_GROUP ""

add_interface_port ready ready irq Output 1


#
# connection point csr
#
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits SYMBOLS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avl_csr__address address Input 10
add_interface_port csr avl_csr__write write Input 1
add_interface_port csr avl_csr__read read Input 1
add_interface_port csr avl_csr__writedata writedata Input 32
add_interface_port csr avl_csr__readdata readdata Output 32
add_interface_port csr avl_csr__waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


#
# connection point pixel_clock
#
add_interface pixel_clock clock end
set_interface_property pixel_clock clockRate 0
set_interface_property pixel_clock ENABLED true
set_interface_property pixel_clock EXPORT_OF ""
set_interface_property pixel_clock PORT_NAME_MAP ""
set_interface_property pixel_clock CMSIS_SVD_VARIABLES ""
set_interface_property pixel_clock SVD_ADDRESS_GROUP ""

add_interface_port pixel_clock pixel_clk clk Input 1


#
# connection point pixel_reset
#
add_interface pixel_reset reset end
set_interface_property pixel_reset associatedClock pixel_clock
set_interface_property pixel_reset synchronousEdges DEASSERT
set_interface_property pixel_reset ENABLED true
set_interface_property pixel_reset EXPORT_OF ""
set_interface_property pixel_reset PORT_NAME_MAP ""
set_interface_property pixel_reset CMSIS_SVD_VARIABLES ""
set_interface_property pixel_reset SVD_ADDRESS_GROUP ""

add_interface_port pixel_reset pixel_rst reset Input 1
